# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_testauth/esi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_testauth/esi.proto',
  package='grpc_testauth.esi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17grpc_testauth/esi.proto\x12\x11grpc_testauth.esi\"N\n\x08\x45siToken\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x14\n\x0c\x63haracter_id\x18\x02 \x01(\x03\x12\x16\n\x0e\x63orporation_id\x18\x03 \x01(\x03\"5\n\x1b\x43haracterAccessTokenRequest\x12\x16\n\x0e\x63orporation_id\x18\x01 \x01(\x03\"l\n\x1c\x43haracterAccessTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12*\n\x05token\x18\x03 \x01(\x0b\x32\x1b.grpc_testauth.esi.EsiTokenb\x06proto3')
)




_ESITOKEN = _descriptor.Descriptor(
  name='EsiToken',
  full_name='grpc_testauth.esi.EsiToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_token', full_name='grpc_testauth.esi.EsiToken.access_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='character_id', full_name='grpc_testauth.esi.EsiToken.character_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corporation_id', full_name='grpc_testauth.esi.EsiToken.corporation_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=124,
)


_CHARACTERACCESSTOKENREQUEST = _descriptor.Descriptor(
  name='CharacterAccessTokenRequest',
  full_name='grpc_testauth.esi.CharacterAccessTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='corporation_id', full_name='grpc_testauth.esi.CharacterAccessTokenRequest.corporation_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=179,
)


_CHARACTERACCESSTOKENRESPONSE = _descriptor.Descriptor(
  name='CharacterAccessTokenResponse',
  full_name='grpc_testauth.esi.CharacterAccessTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='grpc_testauth.esi.CharacterAccessTokenResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc_testauth.esi.CharacterAccessTokenResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='grpc_testauth.esi.CharacterAccessTokenResponse.token', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=289,
)

_CHARACTERACCESSTOKENRESPONSE.fields_by_name['token'].message_type = _ESITOKEN
DESCRIPTOR.message_types_by_name['EsiToken'] = _ESITOKEN
DESCRIPTOR.message_types_by_name['CharacterAccessTokenRequest'] = _CHARACTERACCESSTOKENREQUEST
DESCRIPTOR.message_types_by_name['CharacterAccessTokenResponse'] = _CHARACTERACCESSTOKENRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EsiToken = _reflection.GeneratedProtocolMessageType('EsiToken', (_message.Message,), dict(
  DESCRIPTOR = _ESITOKEN,
  __module__ = 'grpc_testauth.esi_pb2'
  # @@protoc_insertion_point(class_scope:grpc_testauth.esi.EsiToken)
  ))
_sym_db.RegisterMessage(EsiToken)

CharacterAccessTokenRequest = _reflection.GeneratedProtocolMessageType('CharacterAccessTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHARACTERACCESSTOKENREQUEST,
  __module__ = 'grpc_testauth.esi_pb2'
  # @@protoc_insertion_point(class_scope:grpc_testauth.esi.CharacterAccessTokenRequest)
  ))
_sym_db.RegisterMessage(CharacterAccessTokenRequest)

CharacterAccessTokenResponse = _reflection.GeneratedProtocolMessageType('CharacterAccessTokenResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHARACTERACCESSTOKENRESPONSE,
  __module__ = 'grpc_testauth.esi_pb2'
  # @@protoc_insertion_point(class_scope:grpc_testauth.esi.CharacterAccessTokenResponse)
  ))
_sym_db.RegisterMessage(CharacterAccessTokenResponse)


# @@protoc_insertion_point(module_scope)
