# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_testauth/eve.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17grpc_testauth/eve.proto\x12\x11grpc_testauth.eve\"x\n\x11\x45VEPlayerAlliance\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06ticker\x18\x03 \x01(\t\x12\x39\n\x08\x65xecutor\x18\x04 \x01(\x0b\x32\'.grpc_testauth.eve.EVEPlayerCorporation\"\xb6\x01\n\x14\x45VEPlayerCorporation\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06ticker\x18\x03 \x01(\t\x12<\n\rceo_character\x18\x04 \x01(\x0b\x32%.grpc_testauth.eve.EVEPlayerCharacter\x12\x36\n\x08\x61lliance\x18\x05 \x01(\x0b\x32$.grpc_testauth.eve.EVEPlayerAlliance\"\x9c\x01\n\x12\x45VEPlayerCharacter\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12<\n\x0b\x63orporation\x18\x03 \x01(\x0b\x32\'.grpc_testauth.eve.EVEPlayerCorporation\x12\x0c\n\x04race\x18\x04 \x01(\x05\x12\x0e\n\x06gender\x18\x05 \x01(\x05\x12\x10\n\x08total_sp\x18\x06 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_testauth.eve_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVEPLAYERALLIANCE._serialized_start=46
  _EVEPLAYERALLIANCE._serialized_end=166
  _EVEPLAYERCORPORATION._serialized_start=169
  _EVEPLAYERCORPORATION._serialized_end=351
  _EVEPLAYERCHARACTER._serialized_start=354
  _EVEPLAYERCHARACTER._serialized_end=510
# @@protoc_insertion_point(module_scope)
