# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: grpc_testauth/eve.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import grpc_testauth.eve_pb2
