# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_testauth/eve.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_testauth/eve.proto',
  package='grpc_testauth.eve',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17grpc_testauth/eve.proto\x12\x11grpc_testauth.eve\"x\n\x11\x45VEPlayerAlliance\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06ticker\x18\x03 \x01(\t\x12\x39\n\x08\x65xecutor\x18\x04 \x01(\x0b\x32\'.grpc_testauth.eve.EVEPlayerCorporation\"\xb6\x01\n\x14\x45VEPlayerCorporation\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06ticker\x18\x03 \x01(\t\x12<\n\rceo_character\x18\x04 \x01(\x0b\x32%.grpc_testauth.eve.EVEPlayerCharacter\x12\x36\n\x08\x61lliance\x18\x05 \x01(\x0b\x32$.grpc_testauth.eve.EVEPlayerAlliance\"\x9c\x01\n\x12\x45VEPlayerCharacter\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12<\n\x0b\x63orporation\x18\x03 \x01(\x0b\x32\'.grpc_testauth.eve.EVEPlayerCorporation\x12\x0c\n\x04race\x18\x04 \x01(\x05\x12\x0e\n\x06gender\x18\x05 \x01(\x05\x12\x10\n\x08total_sp\x18\x06 \x01(\x05\x62\x06proto3'
)




_EVEPLAYERALLIANCE = _descriptor.Descriptor(
  name='EVEPlayerAlliance',
  full_name='grpc_testauth.eve.EVEPlayerAlliance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc_testauth.eve.EVEPlayerAlliance.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc_testauth.eve.EVEPlayerAlliance.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ticker', full_name='grpc_testauth.eve.EVEPlayerAlliance.ticker', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executor', full_name='grpc_testauth.eve.EVEPlayerAlliance.executor', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=166,
)


_EVEPLAYERCORPORATION = _descriptor.Descriptor(
  name='EVEPlayerCorporation',
  full_name='grpc_testauth.eve.EVEPlayerCorporation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc_testauth.eve.EVEPlayerCorporation.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc_testauth.eve.EVEPlayerCorporation.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ticker', full_name='grpc_testauth.eve.EVEPlayerCorporation.ticker', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ceo_character', full_name='grpc_testauth.eve.EVEPlayerCorporation.ceo_character', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alliance', full_name='grpc_testauth.eve.EVEPlayerCorporation.alliance', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=351,
)


_EVEPLAYERCHARACTER = _descriptor.Descriptor(
  name='EVEPlayerCharacter',
  full_name='grpc_testauth.eve.EVEPlayerCharacter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc_testauth.eve.EVEPlayerCharacter.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc_testauth.eve.EVEPlayerCharacter.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='corporation', full_name='grpc_testauth.eve.EVEPlayerCharacter.corporation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='race', full_name='grpc_testauth.eve.EVEPlayerCharacter.race', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='grpc_testauth.eve.EVEPlayerCharacter.gender', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_sp', full_name='grpc_testauth.eve.EVEPlayerCharacter.total_sp', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=510,
)

_EVEPLAYERALLIANCE.fields_by_name['executor'].message_type = _EVEPLAYERCORPORATION
_EVEPLAYERCORPORATION.fields_by_name['ceo_character'].message_type = _EVEPLAYERCHARACTER
_EVEPLAYERCORPORATION.fields_by_name['alliance'].message_type = _EVEPLAYERALLIANCE
_EVEPLAYERCHARACTER.fields_by_name['corporation'].message_type = _EVEPLAYERCORPORATION
DESCRIPTOR.message_types_by_name['EVEPlayerAlliance'] = _EVEPLAYERALLIANCE
DESCRIPTOR.message_types_by_name['EVEPlayerCorporation'] = _EVEPLAYERCORPORATION
DESCRIPTOR.message_types_by_name['EVEPlayerCharacter'] = _EVEPLAYERCHARACTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EVEPlayerAlliance = _reflection.GeneratedProtocolMessageType('EVEPlayerAlliance', (_message.Message,), {
  'DESCRIPTOR' : _EVEPLAYERALLIANCE,
  '__module__' : 'grpc_testauth.eve_pb2'
  # @@protoc_insertion_point(class_scope:grpc_testauth.eve.EVEPlayerAlliance)
  })
_sym_db.RegisterMessage(EVEPlayerAlliance)

EVEPlayerCorporation = _reflection.GeneratedProtocolMessageType('EVEPlayerCorporation', (_message.Message,), {
  'DESCRIPTOR' : _EVEPLAYERCORPORATION,
  '__module__' : 'grpc_testauth.eve_pb2'
  # @@protoc_insertion_point(class_scope:grpc_testauth.eve.EVEPlayerCorporation)
  })
_sym_db.RegisterMessage(EVEPlayerCorporation)

EVEPlayerCharacter = _reflection.GeneratedProtocolMessageType('EVEPlayerCharacter', (_message.Message,), {
  'DESCRIPTOR' : _EVEPLAYERCHARACTER,
  '__module__' : 'grpc_testauth.eve_pb2'
  # @@protoc_insertion_point(class_scope:grpc_testauth.eve.EVEPlayerCharacter)
  })
_sym_db.RegisterMessage(EVEPlayerCharacter)


# @@protoc_insertion_point(module_scope)
