# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: grpc_testauth/group.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import grpc_testauth.group_pb2
