# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_testauth/group.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpc_testauth/group.proto\x12\x13grpc_testauth.group\"2\n\x05Group\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07sso_urn\x18\x03 \x01(\t\"S\n\x14GroupMembershipEntry\x12)\n\x05group\x18\x01 \x01(\x0b\x32\x1a.grpc_testauth.group.Group\x12\x10\n\x08is_admin\x18\x02 \x01(\x08\"Y\n\x12GroupSearchRequest\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12\x0c\n\x02id\x18\x02 \x01(\x05H\x00\x12\x11\n\x07sso_urn\x18\x03 \x01(\tH\x00\x42\x12\n\x10group_identifier\"R\n\x13GroupSearchResponse\x12*\n\x06result\x18\x01 \x01(\x0b\x32\x1a.grpc_testauth.group.Group\x12\x0f\n\x07success\x18\x02 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_testauth.group_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUP._serialized_start=50
  _GROUP._serialized_end=100
  _GROUPMEMBERSHIPENTRY._serialized_start=102
  _GROUPMEMBERSHIPENTRY._serialized_end=185
  _GROUPSEARCHREQUEST._serialized_start=187
  _GROUPSEARCHREQUEST._serialized_end=276
  _GROUPSEARCHRESPONSE._serialized_start=278
  _GROUPSEARCHRESPONSE._serialized_end=360
# @@protoc_insertion_point(module_scope)
