# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_testauth/main.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_testauth import group_pb2 as grpc__testauth_dot_group__pb2
from grpc_testauth import user_pb2 as grpc__testauth_dot_user__pb2
from grpc_testauth import esi_pb2 as grpc__testauth_dot_esi__pb2
from grpc_testauth import ping_pb2 as grpc__testauth_dot_ping__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_testauth/main.proto',
  package='grpc_testauth',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18grpc_testauth/main.proto\x12\rgrpc_testauth\x1a\x19grpc_testauth/group.proto\x1a\x18grpc_testauth/user.proto\x1a\x17grpc_testauth/esi.proto\x1a\x18grpc_testauth/ping.proto2k\n\x0cGroupService\x12[\n\x06Search\x12\'.grpc_testauth.group.GroupSearchRequest\x1a(.grpc_testauth.group.GroupSearchResponse2\xb5\x02\n\x0bUserService\x12W\n\x06Search\x12%.grpc_testauth.user.UserSearchRequest\x1a&.grpc_testauth.user.UserSearchResponse\x12\x65\n\rServiceSearch\x12,.grpc_testauth.user.UserServiceSearchRequest\x1a&.grpc_testauth.user.UserSearchResponse\x12\x66\n\rGetPapMinutes\x12).grpc_testauth.user.UserPapMinutesRequest\x1a*.grpc_testauth.user.UserPapMinutesResponse2\x82\x01\n\nEsiService\x12t\n\x11GetCharacterToken\x12..grpc_testauth.esi.CharacterAccessTokenRequest\x1a/.grpc_testauth.esi.CharacterAccessTokenResponse2f\n\x0bPingService\x12W\n\x06Search\x12%.grpc_testauth.ping.PingSearchRequest\x1a&.grpc_testauth.ping.PingSearchResponseb\x06proto3')
  ,
  dependencies=[grpc__testauth_dot_group__pb2.DESCRIPTOR,grpc__testauth_dot_user__pb2.DESCRIPTOR,grpc__testauth_dot_esi__pb2.DESCRIPTOR,grpc__testauth_dot_ping__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_GROUPSERVICE = _descriptor.ServiceDescriptor(
  name='GroupService',
  full_name='grpc_testauth.GroupService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=147,
  serialized_end=254,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='grpc_testauth.GroupService.Search',
    index=0,
    containing_service=None,
    input_type=grpc__testauth_dot_group__pb2._GROUPSEARCHREQUEST,
    output_type=grpc__testauth_dot_group__pb2._GROUPSEARCHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GROUPSERVICE)

DESCRIPTOR.services_by_name['GroupService'] = _GROUPSERVICE


_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='grpc_testauth.UserService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=257,
  serialized_end=566,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='grpc_testauth.UserService.Search',
    index=0,
    containing_service=None,
    input_type=grpc__testauth_dot_user__pb2._USERSEARCHREQUEST,
    output_type=grpc__testauth_dot_user__pb2._USERSEARCHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ServiceSearch',
    full_name='grpc_testauth.UserService.ServiceSearch',
    index=1,
    containing_service=None,
    input_type=grpc__testauth_dot_user__pb2._USERSERVICESEARCHREQUEST,
    output_type=grpc__testauth_dot_user__pb2._USERSEARCHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPapMinutes',
    full_name='grpc_testauth.UserService.GetPapMinutes',
    index=2,
    containing_service=None,
    input_type=grpc__testauth_dot_user__pb2._USERPAPMINUTESREQUEST,
    output_type=grpc__testauth_dot_user__pb2._USERPAPMINUTESRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE


_ESISERVICE = _descriptor.ServiceDescriptor(
  name='EsiService',
  full_name='grpc_testauth.EsiService',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=569,
  serialized_end=699,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCharacterToken',
    full_name='grpc_testauth.EsiService.GetCharacterToken',
    index=0,
    containing_service=None,
    input_type=grpc__testauth_dot_esi__pb2._CHARACTERACCESSTOKENREQUEST,
    output_type=grpc__testauth_dot_esi__pb2._CHARACTERACCESSTOKENRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESISERVICE)

DESCRIPTOR.services_by_name['EsiService'] = _ESISERVICE


_PINGSERVICE = _descriptor.ServiceDescriptor(
  name='PingService',
  full_name='grpc_testauth.PingService',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  serialized_start=701,
  serialized_end=803,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='grpc_testauth.PingService.Search',
    index=0,
    containing_service=None,
    input_type=grpc__testauth_dot_ping__pb2._PINGSEARCHREQUEST,
    output_type=grpc__testauth_dot_ping__pb2._PINGSEARCHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PINGSERVICE)

DESCRIPTOR.services_by_name['PingService'] = _PINGSERVICE

# @@protoc_insertion_point(module_scope)
