# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_testauth/main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_testauth import group_pb2 as grpc__testauth_dot_group__pb2
from grpc_testauth import user_pb2 as grpc__testauth_dot_user__pb2
from grpc_testauth import esi_pb2 as grpc__testauth_dot_esi__pb2
from grpc_testauth import ping_pb2 as grpc__testauth_dot_ping__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc_testauth/main.proto\x12\rgrpc_testauth\x1a\x19grpc_testauth/group.proto\x1a\x18grpc_testauth/user.proto\x1a\x17grpc_testauth/esi.proto\x1a\x18grpc_testauth/ping.proto2k\n\x0cGroupService\x12[\n\x06Search\x12\'.grpc_testauth.group.GroupSearchRequest\x1a(.grpc_testauth.group.GroupSearchResponse2\xb5\x02\n\x0bUserService\x12W\n\x06Search\x12%.grpc_testauth.user.UserSearchRequest\x1a&.grpc_testauth.user.UserSearchResponse\x12\x65\n\rServiceSearch\x12,.grpc_testauth.user.UserServiceSearchRequest\x1a&.grpc_testauth.user.UserSearchResponse\x12\x66\n\rGetPapMinutes\x12).grpc_testauth.user.UserPapMinutesRequest\x1a*.grpc_testauth.user.UserPapMinutesResponse2\xd8\x03\n\nEsiService\x12t\n\x11GetCharacterToken\x12..grpc_testauth.esi.CharacterAccessTokenRequest\x1a/.grpc_testauth.esi.CharacterAccessTokenResponse\x12h\n\x0fUpdateCharacter\x12).grpc_testauth.esi.CharacterUpdateRequest\x1a*.grpc_testauth.esi.CharacterUpdateResponse\x12n\n\x11UpdateCorporation\x12+.grpc_testauth.esi.CorporationUpdateRequest\x1a,.grpc_testauth.esi.CorporationUpdateResponse\x12z\n\x15UpdateCharacterSkills\x12/.grpc_testauth.esi.CharacterSkillsUpdateRequest\x1a\x30.grpc_testauth.esi.CharacterSkillsUpdateResponse2f\n\x0bPingService\x12W\n\x06Search\x12%.grpc_testauth.ping.PingSearchRequest\x1a&.grpc_testauth.ping.PingSearchResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_testauth.main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPSERVICE._serialized_start=147
  _GROUPSERVICE._serialized_end=254
  _USERSERVICE._serialized_start=257
  _USERSERVICE._serialized_end=566
  _ESISERVICE._serialized_start=569
  _ESISERVICE._serialized_end=1041
  _PINGSERVICE._serialized_start=1043
  _PINGSERVICE._serialized_end=1145
# @@protoc_insertion_point(module_scope)
