# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_testauth/ping.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_testauth/ping.proto',
  package='grpc_testauth.ping',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18grpc_testauth/ping.proto\x12\x12grpc_testauth.ping\"j\n\x04Ping\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x19\n\x11\x66\x63_character_name\x18\x04 \x01(\t\x12\x17\n\x0f\x66\x63_character_id\x18\x05 \x01(\r\"\"\n\x11PingSearchRequest\x12\r\n\x05token\x18\x01 \x01(\t\"M\n\x12PingSearchResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12&\n\x04ping\x18\x02 \x01(\x0b\x32\x18.grpc_testauth.ping.Pingb\x06proto3'
)




_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='grpc_testauth.ping.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='grpc_testauth.ping.Ping.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='grpc_testauth.ping.Ping.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='grpc_testauth.ping.Ping.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fc_character_name', full_name='grpc_testauth.ping.Ping.fc_character_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fc_character_id', full_name='grpc_testauth.ping.Ping.fc_character_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=154,
)


_PINGSEARCHREQUEST = _descriptor.Descriptor(
  name='PingSearchRequest',
  full_name='grpc_testauth.ping.PingSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='grpc_testauth.ping.PingSearchRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=190,
)


_PINGSEARCHRESPONSE = _descriptor.Descriptor(
  name='PingSearchResponse',
  full_name='grpc_testauth.ping.PingSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='grpc_testauth.ping.PingSearchResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ping', full_name='grpc_testauth.ping.PingSearchResponse.ping', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=269,
)

_PINGSEARCHRESPONSE.fields_by_name['ping'].message_type = _PING
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['PingSearchRequest'] = _PINGSEARCHREQUEST
DESCRIPTOR.message_types_by_name['PingSearchResponse'] = _PINGSEARCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'grpc_testauth.ping_pb2'
  # @@protoc_insertion_point(class_scope:grpc_testauth.ping.Ping)
  })
_sym_db.RegisterMessage(Ping)

PingSearchRequest = _reflection.GeneratedProtocolMessageType('PingSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGSEARCHREQUEST,
  '__module__' : 'grpc_testauth.ping_pb2'
  # @@protoc_insertion_point(class_scope:grpc_testauth.ping.PingSearchRequest)
  })
_sym_db.RegisterMessage(PingSearchRequest)

PingSearchResponse = _reflection.GeneratedProtocolMessageType('PingSearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGSEARCHRESPONSE,
  '__module__' : 'grpc_testauth.ping_pb2'
  # @@protoc_insertion_point(class_scope:grpc_testauth.ping.PingSearchResponse)
  })
_sym_db.RegisterMessage(PingSearchResponse)


# @@protoc_insertion_point(module_scope)
