# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: grpc_testauth/services.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import grpc_testauth.user_pb2
import grpc_testauth.services_pb2
