# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_testauth/services.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_testauth import user_pb2 as grpc__testauth_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgrpc_testauth/services.proto\x12\x16grpc_testauth.services\x1a\x18grpc_testauth/user.proto\"\x16\n\x07Service\x12\x0b\n\x03\x61pi\x18\x01 \x01(\t\"\x8f\x01\n\x0eServiceAccount\x12\x30\n\x07service\x18\x01 \x01(\x0b\x32\x1f.grpc_testauth.services.Service\x12&\n\x04user\x18\x02 \x01(\x0b\x32\x18.grpc_testauth.user.User\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x12\x13\n\x0bservice_uid\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_testauth.services_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICE._serialized_start=82
  _SERVICE._serialized_end=104
  _SERVICEACCOUNT._serialized_start=107
  _SERVICEACCOUNT._serialized_end=250
# @@protoc_insertion_point(module_scope)
