# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_testauth/user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_testauth import group_pb2 as grpc__testauth_dot_group__pb2
from grpc_testauth import eve_pb2 as grpc__testauth_dot_eve__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc_testauth/user.proto\x12\x12grpc_testauth.user\x1a\x19grpc_testauth/group.proto\x1a\x17grpc_testauth/eve.proto\"\x93\x02\n\x04User\x12\x0f\n\x07\x61uth_id\x18\x01 \x01(\x05\x12\x10\n\x08sso_uuid\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12@\n\x11primary_character\x18\x04 \x01(\x0b\x32%.grpc_testauth.eve.EVEPlayerCharacter\x12\x39\n\ncharacters\x18\x05 \x03(\x0b\x32%.grpc_testauth.eve.EVEPlayerCharacter\x12\x39\n\x06groups\x18\x06 \x03(\x0b\x32).grpc_testauth.group.GroupMembershipEntry\x12\x1e\n\x16primary_character_name\x18\x07 \x01(\t\"D\n\x18UserServiceSearchRequest\x12\x13\n\x0bservice_uid\x18\x01 \x01(\t\x12\x13\n\x0bservice_api\x18\x02 \x01(\t\"\x92\x01\n\x11UserSearchRequest\x12\x11\n\x07\x61uth_id\x18\x01 \x01(\x05H\x00\x12\x12\n\x08username\x18\x02 \x01(\tH\x00\x12\x12\n\x08sso_uuid\x18\x03 \x01(\tH\x00\x12\x18\n\x0e\x63haracter_name\x18\x04 \x01(\tH\x00\x12\x15\n\x0bservice_uid\x18\x05 \x01(\tH\x00\x42\x11\n\x0fuser_identifier\"O\n\x12UserSearchResponse\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.grpc_testauth.user.User\x12\x0f\n\x07success\x18\x02 \x01(\x08\"V\n\x15UserPapMinutesRequest\x12&\n\x04user\x18\x01 \x01(\x0b\x32\x18.grpc_testauth.user.User\x12\x15\n\rupto_datetime\x18\x02 \x01(\x03\"5\n\x16UserPapMinutesResponse\x12\x0f\n\x07minutes\x18\x01 \x01(\x05J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_testauth.user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=101
  _USER._serialized_end=376
  _USERSERVICESEARCHREQUEST._serialized_start=378
  _USERSERVICESEARCHREQUEST._serialized_end=446
  _USERSEARCHREQUEST._serialized_start=449
  _USERSEARCHREQUEST._serialized_end=595
  _USERSEARCHRESPONSE._serialized_start=597
  _USERSEARCHRESPONSE._serialized_end=676
  _USERPAPMINUTESREQUEST._serialized_start=678
  _USERPAPMINUTESREQUEST._serialized_end=764
  _USERPAPMINUTESRESPONSE._serialized_start=766
  _USERPAPMINUTESRESPONSE._serialized_end=819
# @@protoc_insertion_point(module_scope)
